Repository nest/nestml, pull requests merged in 2023-09, with the labels that each got.

#843 Fix STDP synapse bug (nest-simulator #2443)
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
  tests/nest_tests/stdp_synapse_test.py
Labels: bug

#956 Fix third factor STDP synapse test
  tests/nest_tests/third_factor_stdp_synapse_test.py
Labels: bug

#955 Add admonition to docs
  doc/running.rst
Labels: documentation

#958 Fix third factor STDP synapse test
  tests/nest_tests/third_factor_stdp_synapse_test.py
Labels: bug

#950 Fix power operator and `elif` functions in NESTML
  pynestml/cocos/co_co_user_defined_function_correctly_defined.py
  pynestml/visitors/ast_power_visitor.py
  tests/cocos_test.py
  tests/invalid/CoCoFunctionNotUnique.nestml
  tests/resources/ExpressionCollection.nestml
  tests/resources/ExpressionTypeTest.nestml
  tests/valid/CoCoFunctionNotUnique.nestml
Labels: bug, enhancement

#962 Disable debug mode in generated code
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
Labels: maintenance

#964 Fix SpiNNaker figure and clean up "Running NESTML" documentation page
  doc/fig/spinnaker_logo.svg
  doc/requirements.txt
  doc/running/index.rst
  doc/sphinx-apidoc/conf.py
Labels: enhancement, documentation
