Repository nest/nestml, pull requests merged in 2024-07, with the labels that each got.

#1071 Replace outdated mentions of ``deliver_spike()``
  doc/tutorials/stdp_windows/stdp_windows.ipynb
  pynestml/codegeneration/printers/spinnaker_c_function_call_printer.py
Labels: bug, documentation

#1077 Fix priority check in case no block defined
  pynestml/codegeneration/nest_code_generator.py
  pynestml/codegeneration/resources_nest/point_neuron/common/SynapseHeader.h.jinja2
Labels: bug

#1075 Add pi predefined constant
  doc/nestml_language/nestml_language_concepts.rst
  pynestml/codegeneration/printers/c_variable_printer.py
  pynestml/codegeneration/printers/cpp_variable_printer.py
  pynestml/codegeneration/printers/nest_variable_printer.py
  pynestml/codegeneration/printers/python_stepping_function_variable_printer.py
  pynestml/codegeneration/printers/python_variable_printer.py
  pynestml/codegeneration/printers/spinnaker_c_variable_printer.py
  pynestml/symbols/predefined_variables.py
  tests/resources/ExpressionCollection.nestml
Labels: enhancement

#1076 Move note about code generator options to the top of the document
  doc/running/running_nest.rst
Labels: refactoring, documentation

#1079 Update funding acknowledgements
  doc/sphinx-apidoc/index.rst
Labels: documentation

#1083 Clean up templates and debug print statements
  pynestml/codegeneration/nest_code_generator.py
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronHeader.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/common/SynapseHeader.h.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/Block.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/PredefinedFunction_emit_spike.jinja2
  tests/nest_tests/print_function_code_generator_test.py
Labels: refactoring
