Repository nest/nestml, pull requests merged in 2024-12, with the labels that each got.

#1144 Clean up NESTML grammar definition
  pynestml/cocos/co_co_user_defined_function_correctly_defined.py
  pynestml/codegeneration/printers/model_printer.py
  pynestml/codegeneration/printers/nestml_printer.py
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/common/SynapseHeader.h.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/ForStatement.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/IfStatement.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/StmtsBody.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/WhileStatement.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.cpp.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/@NEURON_NAME@.py.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/directives_py/Block.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/directives_py/ForStatement.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/directives_py/IfStatement.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/directives_py/StmtsBody.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/directives_py/WhileStatement.jinja2
  pynestml/codegeneration/resources_spinnaker/@NEURON_NAME@_impl.h.jinja2
  pynestml/codegeneration/resources_spinnaker/@SYNAPSE_NAME@_impl.c.jinja2
  pynestml/generated/PyNestMLLexer.py
  pynestml/generated/PyNestMLLexerBase.py
  pynestml/generated/PyNestMLParser.py
  pynestml/generated/PyNestMLParserVisitor.py
  pynestml/grammars/PyNestMLLexer.g4
  pynestml/grammars/PyNestMLParser.g4
  pynestml/meta_model/ast_elif_clause.py
  pynestml/meta_model/ast_else_clause.py
  pynestml/meta_model/ast_for_stmt.py
  pynestml/meta_model/ast_function.py
  pynestml/meta_model/ast_if_clause.py
  pynestml/meta_model/ast_model.py
  pynestml/meta_model/ast_node_factory.py
  pynestml/meta_model/ast_on_condition_block.py
  pynestml/meta_model/ast_on_receive_block.py
  pynestml/meta_model/ast_stmts_body.py
  pynestml/meta_model/ast_update_block.py
  pynestml/meta_model/ast_while_stmt.py
  pynestml/transformers/synapse_post_neuron_transformer.py
  pynestml/utils/ast_utils.py
  pynestml/utils/model_parser.py
  pynestml/visitors/assign_implicit_conversion_factors_visitor.py
  pynestml/visitors/ast_builder_visitor.py
  pynestml/visitors/ast_symbol_table_visitor.py
  pynestml/visitors/ast_visitor.py
  tests/test_nestml_printer.py
  tests/test_unit_system.py
Labels: bug, refactoring, CI

#1150 Friendlier lexer and parser error messages
  pynestml/grammars/generate_lexer_parser
  pynestml/utils/error_listener.py
  pynestml/utils/messages.py
  pynestml/utils/model_parser.py
Labels: enhancement

#1147 Fix bug with `integrate_odes()` for numeric solver
  pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/GSLDifferentiationFunction.jinja2
  tests/nest_tests/resources/aeif_cond_alpha_alt_neuron.nestml
  tests/nest_tests/test_integrate_odes.py
Labels: bug

#1154 Add NESTML 8 citation to documentation
  doc/citing.rst
Labels: documentation
