Repository nest/nestml, pull requests merged in 2024-04, with the labels that each got.

#1002 Change model registration for NEST target
  doc/tutorials/active_dendrite/nestml_active_dendrite_tutorial.ipynb
  doc/tutorials/izhikevich/nestml_izhikevich_tutorial.ipynb
  doc/tutorials/ornstein_uhlenbeck_noise/nestml_ou_noise_tutorial.ipynb
  doc/tutorials/spike_frequency_adaptation/nestml_spike_frequency_adaptation_tutorial.ipynb
  doc/tutorials/stdp_dopa_synapse/stdp_dopa_synapse.ipynb
  doc/tutorials/stdp_windows/stdp_windows.ipynb
  doc/tutorials/triplet_stdp_synapse/triplet_stdp_synapse.ipynb
  pynestml/codegeneration/nest_builder.py
  pynestml/codegeneration/nest_code_generator.py
  pynestml/codegeneration/nest_code_generator_utils.py
  pynestml/codegeneration/nest_compartmental_code_generator.py
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronHeader.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/common/SynapseHeader.h.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/setup/@MODULE_NAME@.cpp.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/setup/@MODULE_NAME@.h.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/setup/common/ModuleClass.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/setup/common/ModuleClassMaster.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/setup/common/ModuleHeader.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/@NEURON_NAME@.cpp.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/@NEURON_NAME@.h.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/@MODULE_NAME@.cpp.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/@MODULE_NAME@.h.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/common/ModuleClass.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/common/ModuleClassMaster.jinja2
  pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/common/ModuleHeader.jinja2
  pynestml/generated/PyNestMLLexer.py
  pynestml/generated/PyNestMLParser.py
  pynestml/generated/PyNestMLParserVisitor.py
  setup.py
  tests/nest_compartmental_tests/compartmental_model_test.py
  tests/nest_compartmental_tests/resources/cm_default.nestml
  tests/nest_tests/fir_filter_test.py
  tests/nest_tests/nest_delay_based_variables_test.py
  tests/nest_tests/nest_instantiability_test.py
  tests/nest_tests/nest_integration_test.py
  tests/nest_tests/nest_loops_integration_test.py
  tests/nest_tests/nest_multithreading_test.py
  tests/nest_tests/noisy_synapse_test.py
  tests/nest_tests/stdp_nn_pre_centered_test.py
  tests/nest_tests/stdp_nn_restr_symm_test.py
  tests/nest_tests/stdp_nn_synapse_test.py
  tests/nest_tests/stdp_synapse_test.py
  tests/nest_tests/stdp_triplet_synapse_test.py
  tests/nest_tests/stdp_window_test.py
  tests/nest_tests/test_forward_euler_integrator.py
  tests/nest_tests/test_gap_junction.py
  tests/nest_tests/test_ignore_and_fire.py
  tests/nest_tests/test_static_synapse.py
  tests/nest_tests/test_time_variable.py
  tests/nest_tests/third_factor_stdp_synapse_test.py
  tests/nest_tests/traub_cond_multisyn_test.py
Labels: maintenance

#1023 add NEST Simulator release version note to NESTML release checklist
  extras/nestml-release-checklist.md
Labels: documentation

#1017 Add dependabot to CI
  .github/dependabot.yml
Labels: enhancement, CI

#1006 Add inhomogeneous Poisson generator NESTML model
  doc/nestml_language/nestml_language_concepts.rst
  doc/tutorials/inhomogeneous_poisson/inhomogeneous_poisson.ipynb
  doc/tutorials/inhomogeneous_poisson/inhomogeneous_poisson.nestml
  doc/tutorials/tutorials_list.rst
  pynestml/cocos/co_co_vector_declaration_right_size.py
  pynestml/cocos/co_co_vector_variable_in_non_vector_declaration.py
  pynestml/codegeneration/printers/latex_function_call_printer.py
  pynestml/codegeneration/printers/nest2_cpp_function_call_printer.py
  pynestml/codegeneration/printers/nest_cpp_function_call_printer.py
  pynestml/codegeneration/printers/nest_variable_printer.py
  pynestml/codegeneration/printers/python_variable_printer.py
  pynestml/codegeneration/printers/spinnaker_c_variable_printer.py
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronHeader.jinja2
  pynestml/symbols/predefined_functions.py
  pynestml/visitors/ast_random_number_generator_visitor.py
  pynestml/visitors/ast_set_vector_parameter_in_update_expressions.py
  pynestml/visitors/ast_symbol_table_visitor.py
  pynestml/visitors/ast_visitor.py
  tests/cocos_test.py
  tests/invalid/CoCoVectorParameterType.nestml
Labels: enhancement

#1043 Fix typos and links in documentation pages
  doc/nestml_language/neurons_in_nestml.rst
  doc/nestml_language/synapses_in_nestml.rst
  doc/running/running_nest_compartmental.rst
  doc/tutorials/inhomogeneous_poisson/inhomogeneous_poisson.ipynb
  doc/tutorials/stdp_dopa_synapse/stdp_dopa_synapse.ipynb
Labels: documentation
