Repository nest/nestml, pull requests merged in 2025-03, with the labels that each got.

#1149 Modify the code generator for the NEST Desktop target
  .github/workflows/nestml-build.yml
  pynestml/codegeneration/nest_desktop_code_generator.py
  pynestml/codegeneration/nest_tools.py
  pynestml/codegeneration/python_standalone_target_tools.py
  pynestml/codegeneration/resources_nest_desktop/@NEURON_NAME@.json.jinja2
  pynestml/codegeneration/resources_nest_desktop/ParameterDeclaration.jinja2
  pynestml/codegeneration/resources_nest_desktop/VariableDeclaration.jinja2
  tests/nest_desktop_tests/nest_desktop_code_generator_test.py
Labels: enhancement

#1178 Remove no longer needed conductance-based flag
  pynestml/symbols/variable_symbol.py
  pynestml/utils/messages.py
Labels: maintenance

#1179 Fix and add test for Izhikevich neuron in Python-standalone target
  pynestml/codegeneration/resources_python_standalone/point_neuron/@NEURON_NAME@.py.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/@SYNAPSE_NAME@.py.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/simulator.py.jinja2
  pynestml/codegeneration/resources_python_standalone/point_neuron/test_python_standalone_module.py.jinja2
  tests/nest_tests/stdp_nn_restr_symm_test.py
  tests/python_standalone_tests/test_izhikevich.py
Labels: bug

#1182 Fix for Astropy 7.0.0
  tests/valid/CoCoVariableWithSameNameAsUnit.nestml
Labels: maintenance

#1183 Temporary fix for STDP trace
  doc/tutorials/stdp_windows/stdp_windows.ipynb
  doc/tutorials/triplet_stdp_synapse/triplet_stdp_synapse.ipynb
  models/synapses/stdp_triplet_synapse.nestml
  pynestml/codegeneration/printers/nest_variable_printer.py
  pynestml/codegeneration/resources_nest/point_neuron/common/SynapseHeader.h.jinja2
Labels: bug

#1174 Add test for parrot neuron
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
  pynestml/codegeneration/resources_nest/point_neuron/common/NeuronHeader.jinja2
  tests/nest_tests/resources/parrot_neuron.nestml
  tests/nest_tests/test_parrot_neuron.py
Labels: bug

#1171 Make distinction between neuron and synapse model interpretation more clear
  doc/running/running_nest.rst
  pynestml/codegeneration/code_generator_utils.py
  pynestml/codegeneration/nest_code_generator.py
  pynestml/codegeneration/nest_code_generator_utils.py
  pynestml/codegeneration/nest_desktop_code_generator.py
  pynestml/codegeneration/pretty_render_code_generator.py
Labels: maintenance

#1189 Fix continuous benchmarking
  .github/workflows/continuous_benchmarking_master_branch.yml
  .github/workflows/continuous_benchmarking_pull_requests.yml
Labels: CI, maintenance

#1177 Limit number of compiler processes
  pynestml/codegeneration/nest_builder.py
Labels: enhancement

#1188 Relax sympy version requirement
  doc/requirements.txt
  requirements.txt
Labels: maintenance
